site_name: InsidePSBS API
site_url: https://app.its-tps.fr
nav:
  - Home: index.md
  - Authentication:
      - Register: authentification/register.md
      - Login: authentification/login.md
      - Logout: authentification/logout.md
      - Forgot password: authentification/forgot-password.md
      - Verify email: authentification/verify-email.md
      - Check: authentification/check.md
      - Availability: authentification/availability.md
  - Users:
      - Get user: users/get.md
      - Update user: users/update.md
      - Delete user: users/delete.md
      - Avatar: users/avatar.md
      - New Password: users/new-password.md
  - Fouaille:
      - fouaille: fouaille/fouaille.md
  - Contents:
      - Store : contents/store.md
      - Create: contents/create.md
      - Events:
          - Index events: contents/events/index.md
          - Show event: contents/events/show.md
      - Posts:
          - Index posts: contents/posts/index.md
          - Show post: contents/posts/show.md
  - Other:
      - sectors: others/sectors.md

theme: readthedocs
