site_name: InsidePSBS API
site_url: https://app.its-tps.fr
nav:
  - Home: index.md
  - Authentication:
      - Register: authentification/register.md
      - Login: authentification/login.md
      - Logout: authentification/logout.md
      - Forgot password: authentification/forgot-password.md
      - Verify email: authentification/verify-email.md
      - Check: authentification/check.md
      - Availability: authentification/availability.md
  - Users:
      - Get user: users/get.md
      - User show: users/show.md
      - Update user: users/update.md
      - Delete user: users/delete.md
      - Avatar: users/avatar.md
      - New Password: users/new-password.md
  - Fouaille:
      - balance: fouaille/balance.md
      - Orders: fouaille/orders.md
  - Contents:
      - Store: contents/store.md
      - Events:
          - Index events: contents/events/index.md
          - Show event: contents/events/show.md
          - Delete event: contents/event/delete.md
      - Posts:
          - Index posts: contents/posts/index.md
          - Show post: contents/posts/show.md
          - Delete post: contents/posts/delete.md
      - Comments:
          - Index comments: contents/comments/index.md
          - Store comment: contents/comments/store.md
      - Reactions:
          - Index reactions: contents/reactions/index.md
          - Store reaction: contents/reactions/store.md
          - Index reactions_type: contents/reactionType/index.md
      - Catégories:
          - Store catégories: contents/category/store.md
          - Index categoriesType: contents/category/index.md
      - Medias:
          - Store Medias: contents/medias/store.md
  - Organizations:
      - Index organizations: organizations/index.md
      - Show organization: organizations/show.md
  - Other:
      - Sectors: others/sectors.md
      - Cgu: others/cgu.md
      - Mps: others/mps.md

theme: readthedocs
